### ISSUE TITLE
all hail the small graduation

### ISSUE THREAD

**Issue by nembenike** [busyLambda/real#1]

**Comment by busyLambda** [comment]
You seem to be an agent of the antichrist also known as the Pacific Fedoration, I will have to evict this issue right now in order to preserve Cascadia.

**Comment by nembenike** [comment]
It seems thine eyes have failed to discern the true meaning behind my message. Worry not, for thine folly is forgivable. What I wrote was laced with a touch of Darksign humour, a jest born of the endless cycle of misery in which we find ourselves. Think not that I mock thee, for such is the only solace we have left in this crumbling world. Now, enough of this prattle. Let us return to this wretched "issue" and see if it can be vanquished before another hollow falls.

**Comment by busyLambda** [comment]
It seems as though you have not received any news of the fact that the world has been burnt to ash. There are no more hollows left, only the ones deep below, but we need not concern ourselves with them. They are a thing of the past, there is no need to bring such relics into our conversation. All we can do now is pray to whomever we may idolize for we do not fucking know the test answers.
